dev501/src/unpackaged/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <formula>LOWER(Last_Name__c  &amp; Email__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Key</label>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/dev501/src/unpackaged/classes/CandidateKey.cls
public class CandidateKey {

	// This method acts as a uniqueness checker for the Candidate object based on the Email__c field
	public static void hasCandidateDuplicates(Candidate__c[] candidates){
	
        	//TODO: Define a map for unique Candidates called "candidateMap" that maps a String to the Candidate
			Map<String, Candidate__c> candidateMap = new Map<String, Candidate__c>();
			
		//TODO: Declare a for loop to cycle through the candidates.
		for ( Candidate__c candidate:candidates){

            		// TODO: Within that loop, check to verify that the email is not null and if it has a value, store the lastName+email in a String called "uKey"
            		if (candidate.email__c != null){
            			String uKey = (candidate.last_name__c).toLowerCase() + (candidate.email__c).toLowerCase();
            			
			// and then check to see if there are duplicate uKeys within this batch of records.  If there are, use addError to prevent them,
						if (candidateMap.containsKey(uKey))
							candidate.addError('Duplicate lastname+email found');
						
			// and if not, add the uKey/candidate combo to the candidateMap.	
						else
							candidateMap.put(uKey, candidate);
            		}
		}

		
  		//Now hit the DB looking for dupes
  		if (!candidateMap.isEmpty()){
	  		for(Candidate__c[] candidatesCheck:[select Id, unique_key__c from Candidate__c where unique_key__c IN :candidateMap.keySet()]) {
				for(Candidate__c candidate:candidatesCheck) {
	  				String currentCandidateId = candidate.Id;
	  				//if there's a dupe and this isn't the current record, then add the error.
	  				if(candidateMap.containsKey(candidate.unique_key__c) && (currentCandidateId != candidateMap.get(candidate.unique_key__c).Id)) {
	     				candidateMap.get(candidate.unique_key__c).addError('Duplicate LastName + Email found in salesforce(id: ' + candidate.id + ')');
	  				}
	  			}
	    		}
  		} 
  	} 
}